# Generated by Django 2.2.12 on 2021-01-31 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
