# Generated by Django 2.2.12 on 2021-01-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpoll', '0002_auto_20210131_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchoice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='choices', to='blogpoll.PostPoll'),
        ),
    ]
