# Generated by Django 2.2.12 on 2021-02-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpoll', '0003_auto_20210131_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postchoice',
            options={'ordering': ['-publish', 'name']},
        ),
        migrations.AlterModelOptions(
            name='postpoll',
            options={'ordering': ['-rank', '-publish', 'name'], 'verbose_name': 'post poll', 'verbose_name_plural': 'post polls'},
        ),
        migrations.AddField(
            model_name='postpoll',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpoll',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postchoice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='blogpoll.PostPoll'),
        ),
    ]
