# Generated by Django 2.2.12 on 2021-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Keep the reviewer identity anonymous'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_approved',
            field=models.BooleanField(default=False, help_text='The comment has been approved by an admin'),
        ),
    ]
