# Generated by Django 2.2.12 on 2021-01-26 10:44

from django.db import migrations, models
import utility.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210105_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='review',
            name='meta_description',
            field=utility.models.TruncatingCharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='review',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Keep the your identity anonymous'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_approved',
            field=models.BooleanField(default=False, help_text='The review has been approved by an admin'),
        ),
    ]
