# Generated by Django 2.2.12 on 2020-10-19 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('meta_copyright', models.CharField(blank=True, max_length=255, verbose_name='Copyright')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos')),
                ('email', models.EmailField(help_text='This is required', max_length=254)),
                ('website', models.URLField(blank=True, help_text="Please start with 'https://www.'", null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='categories.Category')),
                ('location', models.ForeignKey(blank=True, help_text='Please leave empty if 100% virtual', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='locations.Location')),
            ],
            options={
                'verbose_name': 'biashara',
                'verbose_name_plural': 'biashara',
            },
        ),
        migrations.CreateModel(
            name='SameServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_sameservices_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('url', models.URLField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='business.Business')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Network')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='business/photos')),
                ('alt', models.CharField(blank=True, max_length=256, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.Business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='business.SameServices', to='taggit.Tag', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
