# Generated by Django 2.2.12 on 2020-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hide_mail',
            field=models.BooleanField(default=True),
        ),
    ]
