# Generated by Django 2.2.12 on 2021-01-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210105_1031'),
        ('business', '0002_auto_20201228_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'biashara', 'verbose_name_plural': 'biasharas'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='company', to='categories.Category'),
        ),
    ]
