# Generated by Django 2.2.12 on 2020-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20201115_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hide_mail',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='hide_phone',
            field=models.BooleanField(),
        ),
    ]
