# Generated by Django 2.2.12 on 2021-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, help_text='This is required', max_length=254, null=True),
        ),
    ]
