# Generated by Django 2.2.12 on 2020-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20201115_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hide_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='hide_phone',
            field=models.BooleanField(default=True),
        ),
    ]
