# Generated by Django 2.2.12 on 2021-01-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210129_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='company', to='categories.Category'),
        ),
    ]
