# Generated by Django 2.2.12 on 2021-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20210130_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
    ]
