# Generated by Django 2.2.12 on 2020-12-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0002_auto_20201220_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='closed',
        ),
    ]
