# Generated by Django 2.2.12 on 2021-01-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text="Please start with 'https://www.' ", null=True),
        ),
    ]
