# Generated by Django 2.2.12 on 2020-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
